name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  WORKFLOW_NODE_VERSION: 20.x

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.WORKFLOW_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.WORKFLOW_NODE_VERSION }}
      - name: npm install
        run: npm i
        run: npm i prettier
      - name: tests
        run: npm test
      - name: Prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          filter_mode: file
          level: warning
          tool_name: Prettier
