name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  WORKFLOW_NODE_VERSION: 20.x

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.WORKFLOW_NODE_VERSION }}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.WORKFLOW_NODE_VERSION }}
      - name: npm install
        run: npm ci
      - name: tests
        run: npm test